language: objective-c
cache: cocoapods

install:
- gem install xcpretty cocoapods slather -N

script:
- set -o pipefail && xcodebuild test -workspace Example/MTLParseAdapter.xcworkspace -scheme MTLParseAdapter-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick

after_success: slather